### ISSUE TITLE
Read out a plan js / json object?

### ISSUE THREAD

**Issue by mshick** [lorenwest/node-config#208]
Is there any sort of method to read out a plain js object, without all the methods attached? Something like "config.toJSON()" is what I have in mind. I often need to pass config objects places that don't use this module, and find all the additional "stuff" sort of weird / potentially bug causing.

**Comment by markstos** [comment]
This is a dupe of [#155](https://github.com/lorenwest/node-config/issues/155). Find an answer there. 

Since a couple people have asked about this (myself included!), a doc-patch to the main docs or wiki would be welcome to add a hint about this. 

Experienced JavaScripters may already know about the general-purpose tip provided in #155, but it seems there are a lot more people who haven't learned the idiom or don't remember it.

**Comment by mshick** [comment]
Ah, thanks for the pointer. Sure, I'll get a patch up soon.
