### ISSUE TITLE
Is the warning for instance configuration really required?

### ISSUE THREAD

**Issue by sybarite** [lorenwest/node-config#210]
I don't think warnings should not be thrown if the instance is set in the node env, for example by pm2 system. The instance configuration override should be optional.

**Comment by markstos** [comment]
Sorry, I've having trouble understanding your double-negative question. Could you provide an example with the environment variables that are set, the current behavior and the desired behavior?

**Comment by Jokero** [comment]
If we start let's say 4 instances of an app (cluster_mode) by `pm2`, each app will have a value in process.env.NODE_APP_INSTANCE which will be 0 for the first one, 1, 2 and 3 for the next ones.
So in logs I will see annoying messages:
```
WARNING: NODE_APP_INSTANCE value of '0' did match any instance config file names.
WARNING: NODE_APP_INSTANCE value of '2' did match any instance config file names.
WARNING: NODE_APP_INSTANCE value of '1' did match any instance config file names.
WARNING: NODE_APP_INSTANCE value of '3' did match any instance config file names.
```
So are they really needed? Or can we use some flag to disable this behavior?

**Comment by sybarite** [comment]
@markstos Sorry if I was not clear but I think @Jokero has explained it quite succinctly what I wanted to say.

**Comment by lorenwest** [comment]
[NODE_APP_INSTANCE](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_app_instance) is one of many instructions that can be given to node-config to alter it's behavior. Whenever an instruction is given and node-config cannot fulfill that task, it considers it a configuration problem.

If the recommended [strict mode](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_strict_mode) is used this will throw an exception, usually resulting in program termination.  The fact that you're only seeing `WARNING` messages means you're not using the `strict mode` functionality.

It's unfortunate that another node module uses that same environment variable, but if we removed that check, we wouldn't be fulfilling the contract we have with developers to fail fast on potential configuration problems, so they can be addressed before they become bigger problems.

Some options you have are to ignore the warning, or unset the environment variable just before the first `require("config");` and set it back if you need it.  Or fork node-config.

**Comment by sybarite** [comment]
@lorenwest I understand, but I was thinking if we could have a setting which is throws the exception by default but lets us turn off this false positive warning or exception when anyone is using a PM2 process manager. I understand its a third party program but node-config will be effectively throwing a lot of exception when its not really an exception if anytone wants to use strict mode.

I have turned off the strict mode as of now so that the node process does not crash. But would like to know how would I solve this issue? Do I have to stop using PM2 just for this? Its great program to deploy production node js apps.

**Comment by lorenwest** [comment]
Yes, pm2 is a good program, and keeping `strict mode` in place is a good thing.

A quick way around this would be to put this in your application startup:

```
// Moving NODE_APP_INSTANCE aside during configuration loading
var app_instance = process.argv.NODE_APP_INSTANCE;
process.argv.NODE_APP_INSTANCE = "";
var config = require('config');
process.argv.NODE_APP_INSTANCE = app_instance;
```

**Comment by Jokero** [comment]
I read about `strict mode` and don't understand why is it recommended way?

From wiki:
```
When strict mode is enabled, the following conditions must be true 
or an exception will thrown at require-time:

There must be an explicit config file matching NODE_ENV if NODE_ENV is set.
There must be an explicit config file matching NODE_APP_INSTANCE if NODE_APP_INSTANCE is set
NODE_ENV must not match 'default' or 'local' to avoid ambiguity
```
In my apps I always set `NODE_ENV` and often don't have separate configuration for environment, because all necessary data are in default config. I use `NODE_ENV` value to determine whether it is necessary to perform certain actions: send critical error report to email only on production, require additional node modules to simplify development only for local environment, etc. So with `strict mode` my apps will not run, although I don't do anything criminal. If `strict mode` is off, I still will see annoying warnings in logs with no way to disable it. Yes, I can create empty config files, but maybe it would be better to warn only if there are no suitable config files for app (no `default`, no `{deployment}`, no `local`, etc.)?

**Comment by lorenwest** [comment]
node-config helps manage differing configurations based on deployment environment.  If you have no need for deployment specific configurations, my recommendation would be to put all your configurations into one file and not use node-config.

If your project will some day need different configurations based on your deployments, then starting with node-config now will make it easier to manage those differences in the future.  If that's the case, I recommend creating files for the different configurations you use, and place something in each so you don't get warnings.  As your project needs different configurations based on deployment, you'll have a place to put those differences.

Changing the behavior of `strict mode` is not an option, as those people who chose node-config to manage configuration changes based on deployment environments rely on it.

**Comment by wubzz** [comment]
Sorry to necro old issues but I must agree this is a bit over the top. Checks against `NODE_ENV` makes perfect sense, but `NODE_APP_INSTANCE` does not unless running in cluster mode or explicitly setting it yourself for whatever reason one might have.

Since `pm2` always sets this variable - even if not running in cluster mode - all applications using this module in strict mode will crash unless adding an empty `{}` waste-of-space default configuration file `default-0.[ext]` or using hacks such as ones posted above..

Should at least be an option to disable this imo, but can keep it enabled by default. Just my two cents, no ill will..
