### ISSUE TITLE
Provide an environment variable naming convention

### ISSUE THREAD

**Issue by matthewadams** [lorenwest/node-config#218]
Instead of requiring users to explicitly name environment variables in `config/custom-environment-variables.json`, allow the user to specify a prefix, then use an upper case, underscore-delimited convention for corresponding environment variables.  Without it, every time a new config value is added to `default.json` (or any other config file), the `custom-environment-variables.json` file has to be updated, creating the potential for bugs.

For example, consider a `config/default.json` file that looks like the following.
```
{
  "dirs": {
    "in": [
      "../source-data/watched"
    ],
    "out": "",
    "regex": "",
    "format": ""
  },
  "tz": "",
  "webserver": {
    "name": "DEFAULT",
    "port": 8080
  }
}
```
Without this enhancement, I have to keep the following `custom-environment-variables.json` in sync with the rest of my config:
```
{
  "dirs": {
    "in": "MYAPP_DIRS_IN",
    "out": "MYAPP_DIRS_OUT",
    "regex": "MYAPP_DIRS_REGEX",
    "format": "MYAPP_DIRS_FORMAT"
  },
  "tz": "MYAPP_TZ",
  "webServer": {
    "name": "MYAPP_WEBSERVER_NAME",
    "port": "MYAPP_WEBSERVER_PORT"
  }
}
```
With this proposed enhancement, `require(config)` could offer a method that optionally takes a prefix, like the following.
```
var config = require('config').config('MYAPP'); // prefix environment variables with MYAPP
```
This would cause environment variables like the following to be picked up:
```
export MYAPP_OUT=foo
export MYAPP_REGEX='(\d\d\d)'
export MYAPP_WEBSERVER_PORT=34567
export MYAPP_DIRS_IN=/var/folder/foo,/tmp/receive # comma-separated lists by default
```
Separators could also be specified for env vars and multivalued config values, perhaps by providing a configuration object, like this:
```
var config = require('config').config({
  prefix: 'MYAPP',
  envVarSeparator: '__', // double underscore instead of default of single underscore
  arrayValueSeparator: ':', // colon-separated values instead of default comma-separated
  casing: 'none' // don't change case of config keys; other values could be 'lower', 'upper'
}); // prefix environment variables with MYAPP
```
With the above config configuration, these would be picked up correctly:
```
export MYAPP__out=foo
export MYAPP__regex='(\d\d\d)'
export MYAPP__webServer__port=34567
export MYAPP__dirs__in=/var/folder/foo:/tmp/receive
```
This'd be handy dandy and free me from having to keep `custom-environment-variables.json` in sync with the rest of my configuration.

**Comment by lorenwest** [comment]
When a new configuration element is added, it's added to the default.json.  If you want to associate that element with an environment variable, you add it to custom-environment-variables.json.

It took me about as long to type that sentence as to do that work.

Adding complexity in the name of simplifying this process seems like a zero-sum game.  I'd like to hear from others that this process is heavy weight or bug prone enough to justify a solution like this.

**Comment by markstos** [comment]
Using environment variables is already an action-at-distance approach that requires extra care to communicate clearly what's going. 

This proposed patch would eliminate one common tool to figure out how environment variables are being used: With no entry for the environment variable explicitly defined in one of the config files, you could no longer `grep` to find a reference to the config file. 

This is not a complexity I'm interested in seeing in node-config.

**Comment by matthewadams** [comment]
FWIW, there is precedent here from the `Profile` abstractions from the Spring Framework.  See http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/env/SystemEnvironmentPropertySource.html.

**Comment by lorenwest** [comment]
It's ok @matthewadams, how could you know the magnitude of invoking the Spring Framework on a retired Java war vet?

We survived by eating nothing but abstraction for years.  Layers, upon layers, upon layers, until there was nothing more to abstract.  We had no choice - it was abstract, or perish. Sometimes I look at Spring with a kind of fondness, but usually it just produces a nervous tick.

At times I think - should I return to that, or chew on this glass?

**Comment by matthewadams** [comment]
@lorenwest, great reply.  The only thing I can say in defense (and aligned with Spring's mantra) is that this request is to reduce the need for boilerplate, repetitive coding.  Granted that remembering to update your `custom-environment-variables.json` is a minor task, it's also repetitive and annoying.  Surprisingly, while testing my rather smallish app, I realized that I had already forgot to update `custom-environment-variables.json` for one of my config settings!  :)

I understand & appreciate your argument.  My only retort is that Spring brought welcomed pragmatism and engineering excellence to what was for years wildly chaotic and, at times, a very misled Java community.  (And, yes, in full disclosure, I was a Spring fanboy and consultant for years.)

You own this product, so you have the right to make the decisions.  If I have to live with the minor annoyance of remembering to update my `custom-environment-variables.json`, then so be it, but I'd rather not.

**Comment by lorenwest** [comment]
I have to agree with @markstos here - the cost of updating your environment variable map is small compared to not seeing the full mapping, or wondering what the rule was (or the rules were) that ended up with a particular configuration value.

My therapist thanks you for continuing the Spring conversation. I've found that putting a few XML bean definitions under my pillow at night helps ward off the monsters.

**Comment by matthewadams** [comment]
XML bean definitions are so passe, @lorenwest.  [Spring Java Config](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-java) is what the cool kids use now.  In fact, the cool kids have been using it for so long, I'm sure the younger, cooler kids will find a different way soon, just like Facebook -> Instagram -> Snapchat -> ???   :)

**Comment by matthewadams** [comment]
See https://github.com/lorenwest/node-config/pull/222 for separate CEV tool.

**Comment by tombburnell** [comment]
Shame this never made it in. nconf has this feature and it is very useful in certain situations. 

We configure out applications completely using environment variables in accordance with 12 factor app principles. Primarily using the NODE_CONFIG="{ .. }" feature that node-config already supplies. 

We do not wish to create a new build and trigger a release cycle simply to change configuration.

For our passwords though, they come in using custom-environment-variables.json since another system provides them. 

This works great for relatively static values but when we have to provide id/password combinations that are values of an ever growing map, adding them and going through a release cycle, becomes a real pain. 

eg 
```{
"tokens": { 
   "2123" =>  "password1"
   "3423" =>  "password2"
}```

In this case it would be very useful to supply them as CONFIG__TOKENS__2123="password1" and not have to change the default.json file each time as that requires a release, rather than just a config change and restart.

**Comment by markstos** [comment]
My solution is to have a release process just for configuration changes. It includes:

 - running automated test to check the configuration. For example, if a certain configuration is true, this applies that other configuration values should be present. 
 - push the updated config files to the servers
 - restart the Node.js processes. 

The updated config files are also pushed to our "develop" branch, so that the changes will persist when the next normal release happens. 

These config-only deploys are at least 10x faster than normal deploys, which involve a full application test suite run, asset building and processing and other steps.

There is a strong benefit to having all the configuration centralized and checked into source control. I learned that the day when I accidentally a customer's site, along with their configuration values which only existed in production.

**Comment by lorenwest** [comment]
Seriously? You have a release cycle pipeline to guarantee code is properly managed, yet you allow random, undocumented and uncontrolled changes via environment variables and restart a production app?

**Comment by lorenwest** [comment]
It is no accident that `node-config` is opinionated. It doesn't solve every use case, but if you have a team of people working on your app, this library adds tension against bad decisions.
