### ISSUE TITLE
Add a method for outputting a plain JS object (PR welcome)

### ISSUE THREAD

**Issue by mshick** [lorenwest/node-config#223]
Feature request:  

I think it would really benefit this module to formalize the output of a plain javascript object. I know the little one-liner `JSON.parse(JSON.stringify())` but boy, that feels like an opaque weird thing to have in my app code. The need for POJOs is frequent, for instance, using the hapijs server if I attempt to bring any `node-config` object into a config, hapi will fail on the schema validations because of all the additional methods.

Other libraries, such as immutable, that do large amounts of manipulation on objects offer a `toJS` method, which makes a lot of sense to me. As a stop-gap that method could just do the parse/stringify trick, but I think ideally it would access the hidden internal variables and output those directly.

Going even further, I'd make the case that _any_ invocation of `.get()` should actually output a POJO. It feels highly unnatural to me to be carrying around all this baggage when I've clearly made the choice to only grab a portion of my config.

**Comment by markstos** [comment]
+1 for a shortcut for the parse/stringify idiom. 

The proposal to have `get()` returns POJOs is interesting but I still feel on the fence about.

**Comment by mshick** [comment]
Perhaps if the POJO method were added, default to POJO output for get() could be an optional setting?

**Comment by lorenwest** [comment]
Altering the object returned from `get()` isn't an option because the result is an instance of an object with methods that people rely on.  A common pattern is to `get()` a high level config object, and call `get()` on the returned object to get deeper configs.

The standard javascript way of getting a POJO from an object (if there is a standard) is with the `toJSON()` method.  It's a terrible name for what it does, but the built-in `JSON.stringify()` method calls `toJSON()` to get the raw object.

I would support adding a `toJSON()` method to the config class, and having that method create a deep POJO. That way you'd be able to call `toJSON()` on any object returned from `get()`.  

I don't support adding more configurations to the configuration library.  At some point you'd need configuration profiles just to configure the configuration library so it could process your configurations.

**Comment by sandinmyjoints** [comment]
I would love to see a `toJSON` method for this lib.

**Comment by lorenwest** [comment]
Sweet.  This should be a simple addition.  I'll leave this open a while for anyone that wants their picture in the contributors section of the README page :)

**Comment by vjpr** [comment]
+1 for `toJSON()`. I initially tried `get()` and expected to get this behavior.

**Comment by markstos** [comment]
Should we call it `toObject()` instead?  Mongoose makes a distinction for `toObject()` which returns a POJO and `toJSON()` which returns a string.

**Comment by lorenwest** [comment]
The `JSON.stringify` method looks for a method on an object called `toJSON` and calls that to prepare the object for stringification.  Backbone developers have come to understand this as the method which produces the external representation (without all the backbone methods & attributes).

It's an unfortunate name because it's not JSON, but an object prepared for JSON.  Both `toJSON` and `toObject` have their problems, because `toObject` suggests it's not an object in the first place.  I'm leaning towards `toJSON` because it's useful for both this and JSON stringification.

**Comment by markstos** [comment]
OK. Either one works for me. As you point out, there are precedents and concerns for both.

**Comment by cypherq** [comment]
Wouldn't be good to name method `getRaw`? I have something like this in my curreny Hapi.js project, because as @mshick mentioned - you can't pass schema validation using config without getting raw JS object:

```javascript
config.getRaw = function() {
    /* using built in `get` method so we don't need additional errors/exceptions handling */
    return JSON.parse(JSON.stringify(config.get.apply(config, arguments)));
};
```

@lorenwest I can create PR if it fits your expectation.

**Comment by lorenwest** [comment]
To retain backwards compatibility, version 1.0 has a bunch of methods on the config class that will be going away in config 2.0.  See https://github.com/lorenwest/node-config/wiki/Reserved-Words for more details.

With this in mind, 2.0 can only have `get`, `has`, and `utils` as reserved words.  Adding another keyword to the config object will require minimum 1 year period where warnings are produced before we can use it.

Because it's on the `config.util` object vs. the `config` object itself, the `toJSON` name loses it's benefit in also being useful for JSON.stringify(), so that's out of the running.  The two names left are `config.utils.getRaw()`, and `config.utils.toObject()`.  I don't have a strong opinion between the two, but think that `to` is better than `get` because it suggests conversion.

**Comment by markstos** [comment]
I agree about the contation of `to` vs `get`. So the code would become 

```
config.util.toObject(config('something'))
```

?

Seems like as good as it gets given the design goal of minimizing top-level object properties. At least it's more intuitive to read then the parse/stringify combo.  

I could have used this feature today.

**Comment by antony** [comment]
Also thinking this feature would be great as I too am using HapiJS and want to simply pass my cors config directly into the handler.

I'm far less worried about reserved words than I am about having a convenient 'give me just my raw config'.

I'd really like to see this feature!

**Comment by lorenwest** [comment]
What is it about HAPI that cares about an object's prototype when doing validation?  The object returned from get() doesn't have the prototype methods directly injected into it, the prototype methods are correctly in it's prototype.

If you do an Object.keys() for example, you won't get these prototype methods.

This thread has listed a bunch of ways to get a POJO.  Here's another:

```
var myConfigObject = config.get('some config');
myConfigObject.__proto__ = null;
```

**Comment by antony** [comment]
It's Joi in particular which validates, so probably relates to the way Joi
works.

**Comment by mshick** [comment]
I hope @lorenwest can forgive me for the thread-jacking, but I put together a module that operates similar to node-config, but has significantly fewer features and outputs POJOs. Definitely not a full substitute, but I've been using it successfully with some HAPI projects. 

I won't directly link, to preserve some decency, but it's called "ez-config" and is on npm.

**Comment by lorenwest** [comment]
No problems whatsoever.  We're all in this to get work done, and if this makes it easier for someone to get their work done, I'm all in favor.

Here's the link: https://www.npmjs.com/package/ez-config

**Comment by tthyer** [comment]
I have run into the same issue using joi + config, so would really love a POJO method. However, there is a workaround in joi that might be acceptable for @antony: attach `.unknown(true)` to your schema.

**Comment by antony** [comment]
Thanks @tthyer :)
