### ISSUE TITLE
Nested properties, clarification

### ISSUE THREAD

**Issue by bnaoki** [lorenwest/node-config#228]
Given the following 2 files:
```javascript
// default.js
module.exports = {
  s3: {
    endpoint: 'foobar'
  }
};
```
```javascript
// {deployment}.js
module.exports = {
  s3: {
    region: 'us-east-1'
  }
};
```

What is the expected value of `require('config').get('s3')`? I noticed that the returned object contains both `endpoint` and `region`. Assuming that this is the intended behavior, is there a way to force the matching entry from `{deployment}.js` to override any top-level specified entries? That is, since s3 is defined in `{deployment}.js`, it will set its value to just what's specified in `{deployment}.js` and not inherit previously defined keys.

**Comment by lorenwest** [comment]
At the core, `node-config` is designed to extend from a default, so this is the expected behavior.  There is a wiki page that discusses [examining configuration sources](https://github.com/lorenwest/node-config/wiki/Examining-Configuration-Sources), which gives you access to the individual files that make up the end configuration.

Other than that, you can always `require('./config/{deployment}.js').s3` :)

**Comment by lorenwest** [comment]
If you want to un-define something from default.js, you could set the value to null, but the intention is to have all known configuration values defined in default.js, and only specify overrides in the subsequent files.

**Comment by bnaoki** [comment]
Alright, yah, I assumed this was the case. Thanks for clarifying. :). And good job on the library -- this is exactly what I needed for my project and I like how you can specify local override config without checking those in.
