### ISSUE TITLE
Deferred configuration values are not resolved inside arrays (PR Welcome)

### ISSUE THREAD

**Issue by chetzof** [lorenwest/node-config#231]
```
var defer = require('config/defer').deferConfig;
...
module.exports = {
 srcSvgGlob: [
        bprefix + '/plyr/src/sprite/*.svg',
        defer(function (config) {
            return config.images.src + '/*.svg';
        })
    ]
}
...
```

after initialisation, the deffered value is not replaced by actual value

**Comment by markstos** [comment]
Your avatar appears to be yelling, Alex. Nice to meet you, too. 

If it's practical to resolve deferred values within arrays, this is can go in.  It's practical to *merge* values within arrays, but resolving deferred values is a different case, because the size of the array doesn't change. You are welcome to take the first look at the code and see if this looks reasonable.

**Comment by Klortho** [comment]
This is implemented in [PR 318](https://github.com/lorenwest/node-config/pull/318).
