### ISSUE TITLE
question: version of node-config pre 1.0 that supports `.get` accessor?

### ISSUE THREAD

**Issue by jasonkarns** [lorenwest/node-config#239]
Is there a version of node-config before the 1.0 back-incompat version that supports get-style accessors? We're trying to migrate off pre 1.0 but it doesn't seem possible to do a partial migration. Is this true?

**Comment by lorenwest** [comment]
The `.get` accessor was introduced in version 1.0.0 / 2014-07-23, and unless you have issues listed in the [1.0 upgrade docs](https://github.com/lorenwest/node-config/wiki/Upgrading-From-Config-0.x), you should be able to upgrade across the board.  The .get syntax isn't required in 1.0, so earlier clients of node-config will still work via direct access.

Partial upgrades would be problematic.

**Comment by jasonkarns** [comment]
We know our current usage is mutating the config. I was hoping to
completely convert all usage to gets first. Which would have made it easier
to hunt and kill the mutations. Looks like we'll do it the other way 'round.

**Comment by markstos** [comment]
@jasonkarns You could always patch your pre-1.0 version to add just the `get` method, knowing that the change is forward compatible. `package.json` makes it pretty easy to point to Github branch to specify that you want to use a fork.

Since it looks like the primary question was answered here, I'm closing this issue.
