### ISSUE TITLE
Use dependencies instead of devDependencies

### ISSUE THREAD

**Issue by tamtakoe** [lorenwest/node-config#248]
Plugins from `devDependencies` of `package.json` don't install automatically

**Comment by markstos** [comment]
@tamtakoe That is by design. We don't want to depend on every possible configuration file language we support, since any given project will need just one. You should add the dependencies you need to your own `package.json`.

**Comment by tamtakoe** [comment]
Why did you choose this design? Is some additional modules create a significant burden?

**Comment by markstos** [comment]
Yes, there is additional burden with additional modules. Not just for us, but for everyone. Adding all the possible configuration file parsers as dependencies would mean that most of the modules installed would be modules you are not using, but instead for configuration formats that you don't support.   For the maintainers, they would be many more modules to monitor to see if they have security issues are otherwise need "version bumps" so that our declared dependencies stay to date.

You can get the result  you want my maintaining a new project which depends on node-config as well as the dependencies.
