### ISSUE TITLE
Bug: defer'ed values can end up in the final configuration object depending resolution order. AKA "the double-defer bug"

### ISSUE THREAD

**Issue by markstos** [lorenwest/node-config#266]
This is closely related to #265.

Consider the following configuration, where one deferred configuration value refers to another configuration value:

``` javascript
// using defer functions is optional. See example and docs below.
 var defer = require('config/defer').deferConfig


module.exports = {
  a : "value a",
  b : defer(function () {
    return this.a;
  }),
  c : defer(function () {
    return this.b;
  }),
};
```

Regardless of whether #265 is fixed, it's possible that a deferred value will be referenced in another deferred value.   

This happened to us in today in a complex configuration which wasn't easy to spot right away and where it's desirable to have these values to deferred, to eliminate configuration repetition.

The current result is a kind of a "silent failure" where the the deferred function becomes the value of one of the functions, which later becomes a bug in the application. 

Some possible improvements would be:
1. Fail explicitly. Throw an exception noting that nested defer'ed values have been encountered and aren't supported.
2. Resolve-on-demand. When an unresolved is encountered in a defer function, we would resolve it immediately. 

Resolve-on-demand sounds attractive, but has challenges. Right now raw objects are used in the defer functions. We use an explicit method in the functions to access config properties, which would involve changing the syntax of in defer functions (at least if you want this safety check). 

Other possibility might be to modify the 'this' available to defer functions using a custom `get`  key for the properties. When properties were attempted to be read, we could resolve-on-demand.  This custom 'getters' would not be needed on the final object. 

Failing explicitly in this case is simpler.

**Comment by mhsekhavat** [comment]
Another option is to explicitly define dependencies of each deferred value and resolve dependencies of each value [recursively] before resolving it. For example:
```
var defer = require('config/defer').deferConfig
module.exports = {
  a : "value a",
  b : defer(function () {
    return this.c[0].d;
  }, 'c.0'),
  c : defer(function () {
    return [{d: this.a}];
  }, 'a'),
};
```
With this api, it is possible to resolve deferred values with a safe order.

By requiring dependencies to be explicitly defined, API will be still backward-compatible because if someone does not define dependencies, we can conclude that result of function should not be deferred so we can fail if return value was still deferred.

**Comment by markstos** [comment]
@mhsekhavat that sounds like a decent solution.  Any thoughts @lorenwest before one of us proceeds with implementing this?

I became motivated to address after getting bitten by it again today.

**Comment by lorenwest** [comment]
I defer to your expertise in this area. That I'm replying from a beach house in Indonesia with a cocktail next to me has nothing to do with this evaluation.

**Comment by markstos** [comment]
@mhsekhavat Would you be interested in putting together a pull request for your proposed fix? Ideally it would include code, tests and docs for the feature.  The documentation for the `defer()` system is here:

https://github.com/lorenwest/node-config/wiki/Configuration-Files#javascript-module---js

Perhaps there's an additional place it should be documented as well.

**Comment by mhsekhavat** [comment]
@markstos Unfortunately I'm too busy to try implementing it these days. But in two weeks, I will be free and would be glad to make it work.

**Comment by markstos** [comment]
Thanks @mhsekhavat I'll post here if I'm able to work on it first.

**Comment by mhsekhavat** [comment]
Thanks.

**Comment by markstos** [comment]
I worked on this today, but found the implementation "easier said than done". I did get as far as writing a failing test for the case (at least, it fails for me with Node.js 4.4.2), and I updated the `defer()` function. 

What's still missing is the logic to alter the deferred resolution process, so these dependencies are detected and end up being processed first. Here's my branch:

https://github.com/lorenwest/node-config/tree/issue-266-double-defer-bug

Here are some challenges I ran into:

  * It's convenient to express the dependency as a string in dot notation, like `toplevel.secondlevel`. However, in our code base translating between this notation and a location in an object is not abstracted. The logic is embedded in the `getImpl` routine, which is part of the `get()` method. Maybe we should abstract out that logic or add a dependency to handle it, like [dot-notes](https://www.npmjs.com/package/dot-notes) (but the part we need may just be a few lines of code).
  * I tried to call `_iterate` with the dependent value at the right moment, but `_iterate` doesn't usually deal with final deferred values, it deals with the parents of those objects in the config tree structure. But passing the parent object to the `_iterate()` method doesn't easily work, as an infinite loop can be entered when the  first and second deferred values share the same parent.

So, I'm stepping away from this now. I'll either come back and try to approach it from a different angle, or maybe just update my config structure to avoid this more complex double-deferred case.  However,  my configuration has grown so big, it may be easier to fix this issue than avoid it. When looking at any given point on the config file, it's not necessarily easy to see if a value that might be pointed to is a deferred value now, or might become one someday.

**Comment by markstos** [comment]
After sleeping on this, I have different approach to propose. To recap:

## Current Design

### Declaring values as deferred

The `defer()` function returns an instance of a `DeferredConfig` object. The function passed to the `defer()` method is assigned to a the `resolve` method of the new object.

### Resolving deferred values

After the config strucutre has been built, we walk the entire config object recusively looking for values that are an `instanceof` a `DeferredConfig`  object. When one is found, we replace the value the result of calling the `resolve` method on this `DeferredConfig` object.

### Problems with the current design

Deferred values can and do reference other deferred values. If the referenced value happens not to be resolved first, the referencing object will end up referring directly to the deferred object instead of the expected value.

This issue was partly addressed by resolving the values in a predictable order.

## Proposed Design: lazy resolution using getters.

### Declaring values as deferred

The `defer()` function as it does currently, with the addition that it sets a boolean to note that *any* deferred values are present.

### Resolving deferred values

We check a boolean to see if any deferred values are present.  If there are no deferred values present, do nothing.

If deferred values are present, we update all objects and sub-objects in the config data structure to have a [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) method.

The getter method will check if the value is an instance of a DeferredConfig object. It's not, just return the value.

If it is, replace the DeferredConfig object with the result of calling it's `resolve` method.

If the deferred value function references any other deferred values, they will be resolved correctly before being used through the use of getters.

#### Performance

If there no deferred values in use, there's no performance difference. If deferred values were used, there's the minor overhead of using a getter instead of direct property access. However, the deferred functions are only called once. After that, the values returned by the deferred functions are used in their place.

**Comment by lorenwest** [comment]
I'm not a fan of multi-typed variables, especially regarding mixing deferreds with their resolved values. A deferred is one thing, and the resolved value is completely different. You can mask that difference by wrapping these bi-use variables in new deferreds, but that adds unnecessary overhead.

In my opinion, a value is either a value or a deferred.  If it's a value, then you're done.  If it's a deferred, then you can count on that and use it in a promise chain. Try using one of these bi-use variables in a promise chain, and you'll be disappointed.

With that, a deferred config must be used in a promise chain regardless of if it's been resolved previously. You can reuse deferreds as many times in a promise chain as you like, and they'll resolve immediately if they're in a resolved state.

When treating deferreds as deferreds, you don't get into the problem of order. If you have a sub-object that's a deferred you don't treat it like the resolved value - you use it in a promise chain like the deferred it is.

My opinion is that node-config shouldn't be in the business of trying to mask deferreds, or do anything other than represent them in the config structure as the deferreds they are.

By following that convention, we don't introduce the complexities and subsequent workarounds discussed in this thread.

**Comment by Klortho** [comment]
Hi, guys,

It's really a coincidence that I just came on this thread, because I just last week implemented the almost identical functionality in a plugin for Django's settings: [settings-resolver](https://github.com/Klortho/settings-resolver). Here's the meat of the code: [settings_resolver.py](https://github.com/Klortho/settings-resolver/blob/master/settings_resolver.py). It's in Python but pretty straightforward, I even used almost identical terminology to you guys, and, I swear I hadn't seen this before!

Anyway, I realized while implementing it that the *only* way to make it work correctly is through the use of getters. Since, during the evaluation of a deferred, the dependent config values can appear anywhere in an expression, and you can't predict where, then you have to use a getter. Without getters, this functionality will forever be horribly broken, as it is now.

I'm not sure I 100% follow your last comment, @lorenwest , but it sounds like you are suggesting that the deferreds should not get resolved automatically, but that the user should be responsible for keeping track of which values are of which type. I want to suggest that that's not a good solution, for lots of reasons. The main one is that it's overly burdensome, especially when one considers that really complicated configs can be spread over multiple files, and even in separate repos, and some poor new guy tasked with fixing a config problem might not even have access to the original definition. This functionality should be completely transparent, and not make anyone have to think at all, or do any onerous bookkeeping.

I'm hoping this should be pretty easy to implement, by using a special `Resolver` class that has a default catch-all ES5 getter on it -- that's what gets passed into the `defer` function, instead of the *actual* config object. But I see that in your docs you say that ES5 getters are not supported, and I'm wondering is that some sort of universal ban, or just regarding the config object itself?

If it's okay, I'll try to code this up now and send a PR.

**Comment by Klortho** [comment]
Oh, ack, I just remembered, there is no such thing as a default catch-all getter in ES5. Maybe it will be possible to discover the properties that have been defined, and dynamically, on-demand, attach properties to them, that mirror the real config object.

**Comment by Klortho** [comment]
Just an update: I got a pretty good start on this, and I'm convinced that this approach is sound. If you want to see what I'm doing, you can look at [this diff](https://github.com/lorenwest/node-config/compare/master...Klortho:fix-deferreds#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R749). It's not quite working yet, and is peppered with console.log's, but it is very close. I have to quit for the evening.

**Comment by lorenwest** [comment]
What happens when one of these configs is read before it's resolved? How does the client know they're in that situation, and what do you suggest they do when it happens?

It seems you're going through a lot of work to make things easier for the client, but doesn't this all fall apart if the value is accessed before the deferred is resolved?

I may be missing something, but this seems like you're setting yourself up for nondeterministic results based on arbitrary timing.

**Comment by Klortho** [comment]
What happens now? I think, this kind of approach can only help to alleviate those kinds of problems. I read through @markstos 's comments above, again, and realized that this is nearly exactly the approach he was recommending in "lazy resolution using getters."

I know there's a *lot* of features of this library that I'm not aware of. The submodule configuration features are particularly impressive. So, I acknowledge that yes, there might be some hidden nastinesses.

But when I think of that, my next thought is, how are dealing with them now? I believe that the only way to deal with the complexity that is already here, and fix things so that they act in a more uniform and intuitive way, is like this. 

IMO, this approach is aligned with a functional programming style. It treats these config objects as immutable, which they are (or should be). When layers of overrides get applied, conceptually, they don't change the underlying config; rather, they overlay it, providing another step in a pipeline through which all the metadata passes.

To really fix this feature (again, it's my opinion -- I hope I'm not coming across as too arrogant) you have to stop thinking of these deferred as special. A deferred should be able to be used anywhere that any other setting is used, in any kind of expression -- as long as they are properly wrapped in deferreds. 

There are constraints, but they're relatively simple and intuitive (and, I'd venture, simpler than the ad hoc constraints you have now, like sorting.) All the resolution has to happen at the end (or at least, in a uni-directional cascade). So, for example, none of these deferred functions should be allowed to reach out and change global variables, or (worse) change configuration information in some other part of the tree. They could still dynamically bring in new config info, as long as nothing mutates outside the deferred.

If those constraints are met, then, unless I'm missing something really obvious (and I might be!) this will work. All the deferreds are resolved recursively, and it will just work. I'm 95% sure. 

Of course it'll need a lot of testing. I've been looking over the other tickets and doing a little survey of test cases. How important is 100% backward compatibility to you? I think there's a good chance that *fixing* this feature will entail changing some existing quirky behavior, that maybe some user is relying on.

I hope your open to it -- or at least, open to trying it out.

**Comment by lorenwest** [comment]
I haven't chimed in much with the deferred discussion because I don't recommend using the feature.

Others have gotten value, and are either willing to gloss over the nondeterministic nature of these configs, or they've got a custom bootstrap that assures config deferreds are resolved before subsequent file loading via require(). My guess is most people don't understand the issue, are relying on good luck, and would explain config inconsistencies as gravitational forces from the moon.

With no code we could write that makes this deterministic, I don't recommend using this feature or adding a bunch of logic to make it appear to be improved. My wish would be to deprecate the feature but @markstos is a major contributor and I value his opinion.

@markstos - How do you manage the nondeterministic results of this feature?

**Comment by markstos** [comment]
> How do you manage the nondeterministic results of this feature?

So far it's been a mixture of luck and avoidance-- it some cases I avoid using deferred values that reference other deferred values because I know they might resolve in the desired order. 

I thought perhaps that using getters might allow deterministic results with nested deferred values.  I have not looked over @Klortho's proposed related patch to address this, but will.

@Klortho you mention coming from a Djanjo project. What brings you to the land of Node.js and node-config?

**Comment by Klortho** [comment]
I don't see where the non-determinism comes in. Are there race conditions? Or are people asynchronously mutating their states during or after resolving has has taken place? Do you have examples?

@markstos , I actually, these days, very much prefer JavaScript. My time with Python and Django is a form of penance, I guess ...

**Comment by lorenwest** [comment]
By non-deterministic I mean the config can have different values based on factors outside your control, and without your knowledge. The config will have one value before the resolve, and another after the resolve. 

Configs have the same value throughout the life of the app, so a common practice is to load configs into module scoped variables at the top of the module. Node-config is careful to make sure values are available when your module is loaded, but promise based configs can't follow that pattern. Your developers have to know which configs are safe to read on module load, and which to read after the resolve. If they put the getter in the wrong place, or have a bad day and actually need the value before it's resolved, they'll get the wrong value.

Then there's reject. Promises are used for async work. Things like web requests, file reads, etc. If you do enough of these, you know it's a matter of time before they fail. What value does your config have if the underlying promise ends up in a reject?

This is what I mean by non-deterministic. In my experience, the only way to trust a promise is to treat it like a promise. Wait until it's resolved() and have code that does app-specific processing if rejected.

**Comment by Klortho** [comment]
These aren't related to promises at all, and there isn't even anything async going on. I guess the name "deferred" is confusing, since it's what jQuery calls their promises.

**Comment by iMoses** [comment]
@markstos I played with the code and found a way to solve this issue.
I haven't tested it thoroughly, but initial tests looks good.

It works like that:
1. Resolve all `DeferredConfig`
Resolving a `DeferredConfig` will return a promise instead of executing `func`. 
This promise has a custom method `exec`, which we will call after all deferred functions were resolved.
```
function deferConfig (func) {
  var obj = Object.create(DeferredConfig.prototype);
  obj.resolve = function(config, original) {
    var resolve, promise = new Promise(function(res) { resolve = res; });
    promise.exec = function() {
      resolve(func.call(config, config, original));
      return promise;
    };
    return promise;
  };
  return obj;
}
```
1. A. After each `DeferredConfig` is resolved we replace the resolve method with a new version which will `setPath` on the active configuration once the promise has been resolved.
```
if (prop[property] instanceof DeferredConfig ) {
  prop[property] = prop[property].resolve.call(completeConfig,completeConfig, prop[property]._original);
  prop[property].resolve = function() {
    prop[property].then(function (val) {
      util.setPath(t, path.concat(property), val);
    })
  };
}
```
2. Execute the `exec` method which will execute `func`, and resolve the promise with the results.
3. After all promises have been "executed" we execute the altered `resolve` method which will replace all promises with their final values.
This is async but if the user keeps all deferred functions "sync" (resolve within the next event loop) then most likely we won't experience a race condition (need to verify with tests).

Then you can do something like this:
```
var config = {
  a: defer(function (cfg) {
    return cfg.b.then(b => b);
  }),
  b: defer(function () {
    return 'value!';
  }),
};

// OR

var config = {
  value : 'value!',
  a: defer(async function (cfg) {
    const b = await cfg.b;
    return 'my '+b;
  }),
  b: defer(function (cfg) {
    return cfg.value;
  }),
};
```

**Comment by iMoses** [comment]
If we'll be willing to add another dependency...
With the help of [synchronous-promise](https://www.npmjs.com/package/synchronous-promise) I got it to work and pass all tests.

**Comment by lorenwest** [comment]
Dev dependencies for testing are fine, but no runtime dependencies.

**Comment by iMoses** [comment]
@lorenwest seems to me that if you want to solve this issue in a simple manner which uses the async//await/promise syntax, than there's no other way except implementing the same solution within the library.
Other options are available, but none of them are intuitive or elegant (e.g. callback per required variable. even if we offer helpers for composition it's just more boilerplate.
The "positive" side it that this package effects only deferred config.
Think about it.. You can view my code in the [PR](https://github.com/lorenwest/node-config/pull/555)

**Comment by markstos** [comment]
@iMoses Thanks for your work on this project. 

The solution requires a breaking syntax change for defer functions but that could be worthwhile if it fixes the bug. I'm wondering if the backwards compatibility issue could be addressed by combining this solution with using "getters" for defer functions.   Rather than calling "cfg.a.then(...)", "cfg.a" could be implemented with a getter, so that the first time it's called it synchronously resolves a promise, possibly replacing the "getter" with a static value. Do you think that could work?

I'll "defer" to @lorenwest about whether to add a dependency or copy the code we need from syncronous-promise into this project.

**Comment by lorenwest** [comment]
```
SynchronousPromise.reject()
```

**Comment by markstos** [comment]
Looks like related changes were merged, so I'm closing this.
