### ISSUE TITLE
Could use config.get don't throw error if the prop isn't exist?

### ISSUE THREAD

**Issue by XGHeaven** [lorenwest/node-config#278]
I want `config.get` have follow behaves:
- safely, don't throw any error
- if the prop isn't exist, should return `undefined`

I don't if you wander to add above behaves for `config`?

And now, I use follow hack:
```javascript
config._get = get;
config.get = function(prop) {
    if (config.has(prop)) return config._get(prop);
    return undefined;
}
```

**Comment by markstos** [comment]
All valid keys should be defined in the configuration. If they are
intentionally optional, set them to 'null'. Only 'undefined' values through
errors.

To check if a config key is set, use `config.has()`.

See these related tickets:

https://github.com/lorenwest/node-config/issues/173
https://github.com/lorenwest/node-config/issues/200

The current design is intentional. Our idea of safety is finding out when
you have a broken configuration through an exception for a missing or
typo'ed config key. This avoids garbage-in/garbage-out bugs because the
configuration system returned undefined and that pass through your code
until it blows up at some other spot.

Optional keys are supported between the difference from `undefined` and
`null` and `config.has()`.


On Wed, Dec 23, 2015 at 3:10 PM, Xu Tianyang <notifications@github.com>
wrote:

> I want configget have follow behaves:
>
>    - safely, don't throw any error
>    - if the prop isn't exist, should return undefined
>
> I don't if you wander to add above behaves for config?
>
> And now, I use follow hack:
>
> config_get = get;configget = function(prop) {
>     if (confighas(prop)) return config_get(prop);
>     return undefined;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/issues/278>.
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos
