### ISSUE TITLE
How do I force a recalculation

### ISSUE THREAD

**Issue by mylowillem** [lorenwest/node-config#282]
How do I force the configuration to refresh? E.g. if I change environment variables and want the config to recalculate based on the new variables.

**Comment by lorenwest** [comment]
[Immutable configurations] (https://github.com/lorenwest/node-config/wiki/Upgrading-From-Config-0.x#immutable-configurations) has been a core feature of node-config since version 1.

Modules often hold references to these configurations on load.  Altering configurations ends up with differing values throughout the application.
 
The answer is to restart the application.

**Comment by markstos** [comment]
Or depending on the case, move the dynamic value out of the configuration system.
