### ISSUE TITLE
Loading environment via a different env var

### ISSUE THREAD

**Issue by lostthetrail** [lorenwest/node-config#302]
Is there a way to load the environment via a custom environment variable?

I ask because performance dictates we run NODE_ENV=production almost everywhere, other than development locally. But we still have services and properties which are environment specific.

I was hoping to be able to use something like "OUR_ENV=test NODE_ENV=production" and tell node-config to get it's information from "OUR_ENV".

I would be happy to add this feature if it would be acceptable and doesn't exist.

**Comment by markstos** [comment]
@lostthetrail No, this feature doesn't exist and isn't planned.

The best workaround I'm aware of is to set  NODE_ENV as node-config needs it just before `require`'ing  node-config the first time. Then reseting the value for your other use case as soon as that `require` call is done. 

After the first `require`, node-config is cached in memory and will ignore the new value of NODE_ENV, even if it has changed. 

Since the first load could happen somewhere in bootstrapping code, the usual use of `require('config')` in most modules would require not changes or extra code.

**Comment by lostthetrail** [comment]
@markstos If I were to put in a PR, it wouldn't be considered?

**Comment by markstos** [comment]
@lostthetrail  node-config has over 200,000 downloads per month, and requests to add new bits of complexity arrive about once per week. Taken alone, each request seems somewhat reasonable. Taken together, they would a mountain of complexity and documentation for options that were often only ever requested by a single user among thousands.

It would be more likely to considered if there were a number of other users who were interested in the same thing.

In this case, it seems perhaps equally a flaw that some other part of infrastructure requires declaring that nearly everything is "production".

**Comment by travi** [comment]
While I understand that this won't make a big impact, I'll throw my vote in for this being an option. 

A large portion of the node community does seem to have gravitated to to using only two values for `NODE_ENV`. Locally, it should not be set to `production`, but in any deployed environment, it should be set to exactly that. In our situation, even in our production environment, `prod` as its identifier, which conflicts with the very strong node convention.

I came to the documentation today because we've landed in a spot where we would like to align to the convention of `NODE_ENV` being set to `production` in all deployed environments, but read the actual environment value from another environment variable, which is already configured as `ENVIRONMENT` on all of our servers.

**Comment by lorenwest** [comment]
In your bootstrap:
```javascript
process.env.NODE_ENV = process.env.ENVIRONMENT
require('node-config')
```

`node-config` doesn't need to be infinitely configurable when solutions to edge cases are so simple.

**Comment by travi** [comment]
There are lots of simple solutions to getting `$NODE_ENV` to be equal to `$ENVIRONMENT`, but what I was trying to describe was the desire to have `$NODE_ENV` set to `production` in all deployed environments while getting `node-config` to read the true environment from `$ENVIRONMENT` directly.

**Comment by markstos** [comment]
And if you don't want to alter NODE_ENV,

just set it back after the `require` line for node-config.

    Mark

On Tue, May 24, 2016 at 4:35 PM, Loren West <notifications@github.com>
wrote:

> In your bootstrap:
>
> process.env.NODE_ENV = process.env.ENVIRONMENTrequire('node-config')
>
> node-config doesn't need to be infinitely configurable when solutions to
> edge cases are so simple.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/issues/302#issuecomment-221383074>
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos

**Comment by travi** [comment]
yes, you've already made your stance clear as well as your suggested work arounds. i was simply expressing interest as mentioned in a previous comment mentioning interest from multiple users, nothing more.
