### ISSUE TITLE
Normalize configuration

### ISSUE THREAD

**Issue by philippevk** [lorenwest/node-config#319]
Hi!

It would be neat to be able to define a list of normalization methods for specific config keys so that (for example) you can make sure a file path ends with a slash. Since the configurations are immutable it could be implemented as a special file (ex. normalize.js) that defines an object such as:

``` JavaScript
{
  "foo": value => value + '/',
  "foo.bar": value => value.toLowerCase(),
}
```

or simply as a function

``` JavaScript
function normalizeValue(key, value) {
  // return normalized value
}
```

Is this something you would consider doing? Or is there already some other way to do this?

**Comment by markstos** [comment]
I'm not in favor of adding this (but I'm not the primary maintainer either). 

The way I solve the slash-vs-no-slash in my own configuration file is to put a comment right above the line that tells the developer whether the URL should end in a slash in our not. That has worked well enough for me. 

I also use a second pattern: If there are configuration values that I'm worried might end up wrong or invalid, I write a unit test for them. (We have dozens of config files for customers and are constantly adding new ones). 

I recommend having strictness in the values in your config files and enforcing that with testing, rather than allowing sloppiness in the configuration files and having the code paper it offer. 

If your configuration files are in JavaScript, you also have the option to use a computed configuration value based on other configuration values. See the docs here:

https://github.com/lorenwest/node-config/wiki/Configuration-Files#javascript-module---js

Using that feature, you can also accomplish what you want:

```javascript
module.exports = {
   foo :     "some url",
  normalizedFoo : defer(function () {
      return this.foo + '/';
 }),
};
```

**Comment by philippevk** [comment]
That would work! Didn't know about defer. Thanks!
(I'll put this in local.js so I can keep my base config in yaml)
