### ISSUE TITLE
[Question] No option to set properties to the configuration files ? 

### ISSUE THREAD

**Issue by msuiche** [lorenwest/node-config#331]
Hi,

I only saw the .get() and .has() methods and the util class doesn't provide any members to update or set config variables.

Am I missing something ?

Thanks,

**Comment by lorenwest** [comment]
No, you're not missing something. By design, configurations are immutable throughout the lifetime of the application. Aside from some back doors during bootstrap, once configurations are accessed using get(), their values are immutable.

This is what defines an app configuration from other application data. Once you open the doors to mutability, you become an application database with needs well beyond configuration. 

See packages such as consul.io to understand the implications of mutable configurations.
