### ISSUE TITLE
Config file/property encryption

### ISSUE THREAD

**Issue by tlenex** [lorenwest/node-config#361]
Is it possible to store/read some sensitive data encrypted for this package?
It would be nice to not show any production credentials as plain text in my repository.

**Comment by lorenwest** [comment]
I'm no security specialist, so take this advise with that caveat:

There's nothing preventing you from storing encrypted data in clear text in your configuration files. Decryption keys could be private to the deployed server, and depending on your encryption technique it could be very difficult to make use of the clear text encrypted data.

Node-config is well suited for this because it lets you separate configs by deployment and server.

**Comment by markstos** [comment]
There are a number of patterns out there for dealing with secure data in configuration. node-config has no built-in support for encryption, if that's what your asking. You can still use several patterns with it, like putting sensitive data in environment variables, committing encrypted data to `git` or pulling down sensitive data dynamically.
