### ISSUE TITLE
config.hasGet?

### ISSUE THREAD

**Issue by joh-klein** [lorenwest/node-config#373]
Sorry if this has been asked before (I am pretty sure it has, just can't find it): did you ever consider implementig something like a "hasGet" (for lack of a better word)? Basically this:

```
const confHasGet = (config, propPath) => {
	return config.has(propPath) && config.get(propPath);
};
```

**Comment by lorenwest** [comment]
Good question - I'm not sure it's been asked before. 

I'm not a fan of this because a non-existent configuration is a different thing from an existent configuration with falsy value, but this would mask that difference. As a shorthand it promotes a coding style that mixes error conditions with valid config values.
