### ISSUE TITLE
Webpack : Node target - complaining about missing modules

### ISSUE THREAD

**Issue by jgrauel** [lorenwest/node-config#387]
When I do a compile for node to create server side code, and using a .json config file.
I am getting the modules not found...
Module not found: Error: Can't resolve 'iced-coffee-script' in '/Volumes/_mod/development/git.mod-api/node_modules/config/lib'
i get the same for coffee-script, yaml, hjson, toml, cson, properties, x2js, 
I am wondering if its an issue with web pack configuration file or something else I need to change.

**Comment by markstos** [comment]
@jgrauel, if you had simply searched the project for the term "webpack" for opening a new issue, you would have found 1 wiki page and 10 other issues on the topic that would have answered your question.

https://github.com/lorenwest/node-config/search?utf8=%E2%9C%93&q=webpack

**Comment by benoj** [comment]
No need for the tone of that response - this puts people off collaborating in OS projects

**Comment by markstos** [comment]
@benoj what would your improved alternate response have been?

**Comment by lorenwest** [comment]
Maybe something along the lines of

See this for the history of this issue: https://github.com/lorenwest/node-config/search?q=webpack&type=Issues&utf8=%E2%9C%93

**Comment by benoj** [comment]
I think @lorenwest gave a great answer here 

@markstos any issue is feedback on a project. In this particular case, I would assume that because this person was asking a similar question to what has been asked many times it is likely an issue with *how* that information is presented. 

So rather than give sharp responses to unsuspecting consumers of the library, I would add more prominent links to common issues (as happened in this commit f45ebe1cb20b3404bbed409263438db4fe1f634b - I assume there has been less repetitive questions since then)

**Comment by markstos** [comment]
@lorenwest @benoj Thanks for the feedback. I think the commit you may have meant to refer to is https://github.com/lorenwest/node-config/commit/c7bf651173296a6152aa1e37e051f440ed66bebb where I linked to Webpack-specific docs from the main README. It's true that since that was done, we haven't had new issues raised about it that I recall.

**Comment by markstos** [comment]
For anyone else who ends up here and reads this far, the wiki page on webpack usage is here: https://github.com/lorenwest/node-config/wiki/Webpack-Usage

@lorenwest I see you re-opened this issue. Is there some further action you had in mind to take here regarding webpack compatibility?

**Comment by lorenwest** [comment]
Nope - just pushed the wrong button.
