### ISSUE TITLE
Environment variables from dotenv not read

### ISSUE THREAD

**Issue by romainPrignon** [lorenwest/node-config#402]
Hello, It seems that node-config doesn't read my process.env when I set a variables with `dotenv` in a .env file. Am'I missing something ?

`package.json`
```json
{
    "config": "latest",
    "dotenv": "latest"
}
```

`config/default.json`
```json
{
  "secret": "a really secret thing"
}
```

`config/custom-environment-variables.json`
```json
{
  "secret": "STARTER_PACKAGE_JS_SECRET"
}
```

`.env`
```
STARTER_PACKAGE_JS_SECRET=my_test_env_secret
```

Here is my test
```js
import {config} from 'dotenv'
config()
import {secret} from 'config'

describe('(Config) secret', () => {
  it('should be defined', () => {
    expect(process.env.STARTER_PACKAGE_JS_SECRET).toBe('my_test_env_secret')
    expect(secret).toBe('my_test_env_secret')
  })
})
```

here is the result
```
Failures:
1) (Config) secret should be defined
  Message:
    Expected 'a really secret thing' to be 'my_test_env_secret'.
  Stack:
    Error: Expected 'a really secret thing' to be 'my_test_env_secret'.
        at Object.<anonymous> (/home/romainprignon/workspace/romainprignon/starter-package-js/spec/config.js:9:34)

```

so, process.env.STARTER_PACKAGE_JS_SECRET have the right value but node-config can't see it ?
Tell me if there is something more I can do :-)

**Comment by markstos** [comment]
From your test, it's not clear which of the two `expect()` assertions is throwing, because they are set to compare the exact same values. Try putting them in two different `it()` clauses to clarify.

It appears the problem may be with `dotenv` getting the values into `process.env`, which is not our problem.

**Comment by romainPrignon** [comment]
`test`
```js
describe('(Config) secret', () => {
  it('secret from config : should be defined', () => {
    expect(secret).toBe('my_test_env_secret')
  })
  it('process.env.STARTER_PACKAGE_JS_SECRET : should be defined', () => {
    expect(process.env.STARTER_PACKAGE_JS_SECRET).toBe('my_test_env_secret')
  })
})
```

`result`
```
Failures:
1) (Config) secret secret from config : should be defined
  Message:
    Expected 'a really secret thing' to be 'my_test_env_secret'.
  Stack:
    Error: Expected 'a really secret thing' to be 'my_test_env_secret'.
        at Object.<anonymous> (/home/romainprignon/workspace/romainprignon/starter-package-js/spec/config.js:7:20)
```

`process.env` is set correctly from `dotenv` so maybe there something wrong with my setup ?
Or maybe node-config read the content before dotenv

**Comment by markstos** [comment]
You are not using the `node-config` API correctly.

    var config = require('config');
    var secret = config.get('secret');

Also, `config` is a singleton. If you loaded somewhere else before before `dotenv` was loaded, that could be the issue.

**Comment by siwalik** [comment]
### I confirm that this issue is still persistant as of version 1.30.0 

example :

`config file ` > 
`  {consumer_key: process.env.secret || 'xxxxx'},`

`.env file ` > 
`  process.env.secret = 'aaaaa',`

`myCode.ts ` >>>
`  console.log(config.get('vault.consumer_key')); // xxxxx`
`  console.log(process.env.secret); // aaaaa`

**Comment by gigi** [comment]
Hi! Any updates on this?

**Comment by lorenwest** [comment]
What's an `.env` file? Doesn't appear to be [documented](https://github.com/lorenwest/node-config/wiki/Configuration-Files).

**Comment by gigi** [comment]
@lorenwest seems there is no problem in `node-config` lib 😃 

@siwalik @romainPrignon try to load `dotenv.config()` before any other calls. 
I use https://github.com/cvrabie/inversify-config-injection which uses `node-config`. 
So this import order solves the problem.
```ts
import * as dotenv from "dotenv";
// dotenv order matters
dotenv.config();

import * as http from "http";
import {Container} from "inversify";
...
import {EagerBinder} from "inversify-config-injection"; // this import loads all process.env.* vars
...
```

**Comment by siwalik** [comment]
Thanks for the fix @gigi , I found out another fix for this issue so tagging @romainPrignon along!

Create a file in your root directory called local.js and put your dev credentials there within a module.exports {} like this.

```
module.exports = {
  remoteServer: {
    'mysql': {
      port: '32791',
    },
  },
};
```
That's it. This will act as your local environment file which overwrites your creds on dev. environment.

**Comment by gary-menzel** [comment]
I coming to this a couple of years later and encountered a similar issue using ES6 imports.

The execution order of `import` cannot be guaranteed.  All `import` statements are hoisted to the top of the module that imports them and are executed before any other code on in the body.  So `dotenv.config()` is mostly likely going to be executed AFTER `import config from 'config'` meaning that the `process.env` will not have been updated by the `dotenv` module.

The solution I used to address this is to import `config` dynamically (using the `import()` function) with an `async/await`.  I have a single module in my application that does this that is imported by other modules (i.e. they don't import `config` directly).  In this way, you can be sure that by the time `config` is loaded (dynamically) that `dotenv` will have been able to update `process.env` so that `custom-environment-variables.EXT` will work. 

I don't use dynamic imports very often - but, in this case, it addresses the issues fairly easily.

Sorry to add to this so late after it was closed, but maybe others trying to do the same thing will benefit from this.  Most of the solutions above used `require` which works differently to `import`.

@gigi I did try to control the ordering in a similar manner to your solution - but I am not using those packages and it didn't work with a simple `dotenv.config()` followed by `import config from 'config'`.  The difference could be coming from the TS compilation of the `import` statements - whereas, I am using the native `import` statement from `node 14+` and am not using TS.

**Comment by docmattman** [comment]
@gary-menzel , I'm coming in here late as well, but hitting the same issue.  The fix you mentioned makes sense.  Do you happen to have the code you used to solve this?  I'm interested in trying the same thing to see if I can get it fixed up.  I'm using Rollup and it's hoisting `config` above `dotenv` so my .env values aren't getting set before config executes.

**Comment by gary-menzel** [comment]
> @gary-menzel , I'm coming in here late as well, but hitting the same issue. The fix you mentioned makes sense. Do you happen to have the code you used to solve this? I'm interested in trying the same thing to see if I can get it fixed up. I'm using Rollup and it's hoisting `config` above `dotenv` so my .env values aren't getting set before config executes.

I think this is the code I was using but I dont know if it still works:
```javascript
import path from 'path'

import dotenv from 'dotenv'

dotenv.config()

// !NOTE: we do it this way to ensure that `dotenv` is able to update process.env before `config` loads
const loadConfig = async () => {
  const {default: config} = await import('config')  
  config.data = path.resolve(config.data)
  return config
}

const result = await loadConfig()

export default result

```
