### ISSUE TITLE
Add Mocking Functionality for Testability of Node Apps

### ISSUE THREAD

**Issue by AlecHFerguson** [lorenwest/node-config#423]
I have a node app which uses the `config` module.  I would like to unit test that code with different versions of the configs.  Trouble is, it's not so easy to mock `config`.  After digging through this module's code I found that I could set `process.env.ALLOW_CONFIG_MUTATIONS = true` at the top of the test file.  Then I can modify configs:

```
config[someValue'] = 3
```

The problem with that approach is that subsequent tests may use that new config value and thus be affected by the previous test.  You have to remember to "reset" the values in an after block.  Another option is to delete the require cache and re-require config, though that seems a bit kludgy.

Is there a better way to mock out the behavior of the config module in a unit test?  Dependency injection, perhaps?  I propose a more idiomatic approach, and I would be happy to try coding it up.

```
const config = require('config')
// This copies the original, immutable configs as a new, mutable object.  Config will reference that
// new object from now on.  The original, immutable object is preserved.
config.allowMocks()

describe('multiplyConfigByThree', () => {
  afterEach(() => {
    // This "restores" the config object by re-copying the original, immutable object to the
    // "new", mutable object
    config.restoreOriginal()
  })
  it('Behavior with someValue set to 1', () => {
    config.mock('someValue', 1)
    const result = multiplyConfigByThree()
    expect(result).to.eql(3)
  })
  it('Behavior with someValue set to 4', () => {
    config.mock('someValue', 4)
    const result = multiplyConfigByThree()
    expect(result).to.eql(12)
  })
})
```

Does that sound feasible?

**Comment by markstos** [comment]
First, tests can modify the config file before the first call to `config.get`, when the configuration becomes immutable.  So I don't see a need for `config.allowMocks()`, you can just modify the config structure before you call get.

Second, as documented on the wiki plugins page, you can use [`node-config-uncached`](https://github.com/MrBoolean/node-config-uncached) to get a fresh copy of the configs based on the config file.    So I dont' see a need for `config.restoreMocks()`, since this is what `node-config-uncached` does. 

I see what you've run into as more of documentation problem. It could be helpful to better document how to test different configurations. Perhaps a new wiki page on the topic would be appropriate: https://github.com/lorenwest/node-config/wiki

**Comment by AlecHFerguson** [comment]
Oh cool.  Yeah, I figured this functionality existed somewhere.  Lemme give this a whirl, and maybe add a Wiki page entitled *Testing With Config*?  I'm happy to write it up if you'd like.

If this approach doesn't meet my needs then I'll update this ticket.

**Comment by markstos** [comment]
The wiki page you propose sounds great.

Thanks.

I also need to test alternate configs.  This use-case is a reason why the
object is not immediately immutable.

This is also why node-config-uncached was developed.

**Comment by jcollum-cambia** [comment]
I'm trying to accomplish the same thing with "import-fresh". Anyone who knows about this want to answer this question: https://stackoverflow.com/questions/46369745/how-do-i-override-config-values-at-runtime-with-node-config ? Because it seems like nothing I'm doing to override the configs is working.

**Comment by g-sam** [comment]
I would be in favour of the original suggestion. I'd rather not have to add another dep, which hasn't been updated in two years. Also, I'm guessing it wont work with Jest because you cannot clear the require cache in the normal way.

**Comment by AlecHFerguson** [comment]
Sounds like there's some interest? I'd be happy to take a shot at coding it up and submit a PR if folks would find it useful.

**Comment by lorenwest** [comment]
I would most be interested in figuring out how to mock config without adding code to config. 

Big points for adding a wiki page on using [proxyquire](https://github.com/thlorenz/proxyquire) or similar for mocking vs. changing config.

**Comment by jcollum-cambia** [comment]
How's this: 

https://github.com/lorenwest/node-config/wiki/Altering-configuration-values-for-testing-at-runtime 

I noticed I could clone and PR after I made the edits :/

**Comment by lorenwest** [comment]
That looks great! Thanks for the addition, and no problem making changes directly to the wiki.
