### ISSUE TITLE
Allow default values for config retrieval

### ISSUE THREAD

**Issue by BrainMaestro** [lorenwest/node-config#442]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [  ] bug report
  - [x] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### Problem
`config.get('property')` gets a property for a config (obviously). I would like a way to provide a default value if that property is missing or undefined. Currently, there are two ways of handling this:

1. `config.get('property') || 10`. This is easy and does not require any library modifications. However, it fails for falsy values like `false`, `''`, or `0` which could be valid configs. 
2. Using a more explicit `typeof` or strict equality check. This is more accurate, but it litters the code with unnecessary if statements. If there were 5 config retrievals, the check would be duplicated each time.

### Proposal
Allow the user to provide a default in case the value is undefined or null. This would look like `config.get('property', 10)`. Elegantly solves the problem with little duplication.

#### Prior Art
https://github.com/illuminate/config/blob/master/Repository.php#L47

I would be willing to implement this if it is accepted

**Comment by lorenwest** [comment]
I'd support a pull request for this feature.

**Comment by markstos** [comment]
This feature request was previously discussed and rejected in #393 and #381

I believe this feature is harmful.  The current design encourages that all default values should be in the config system, where they belong.

Adding the ability to set defaults in the code confuses where they belong. Should default values still be in `default.js`, or should they now be sprinkled throughout the code? Or some mix? 

Before my large project used `node-config`, we had a simpler config system, and a lot of default values sprinkled throughout the code base.  It was a pain to understand the configuration as a whole because it was spread across the entire codebase in adhoc locations. Sometimes this kind of "default" syntax gets used in multiple locations with different values, so there ends up being three different "default" values stored in three different locations. Bad. 

If you are tempted to use `config.get('property') || 10`, then `10` is a magic number, a constant that belongs in your config system, not in your code. Put in in `config/default.js`.

Consider a more complex case: In one location you do: ``config.get('property') || 10` but in another location you do ``config.get('property') || 20`.  So now the default value for `property is stored in 3 locations: Once in the config system, as well as two different locations in the code, which happen to disagree with each other.  If you've got a case like that, then you have an stronger need to add both values to config system so you give them different  names to explain why the value "10" is appropriate in one place in the value "20" is the correct value in another.

**Comment by lorenwest** [comment]
Thank you for remembering. It felt too easy to be true...
