### ISSUE TITLE
Config.get() causes config to become readonly.

### ISSUE THREAD

**Issue by tombburnell** [lorenwest/node-config#454]
### I'm submitting a ... 
  - [ x ] bug report
  - [  ] feature request

### What is the current behavior?
Config is writable (desired) up until calling config.get(..) at which point it becomes readonly.

default.json
{ 
  field: "foo"
}

let c = require("config");
c.field = "bar"
console.log(c) 
// { field: "bar" }
c.get("field");
c.field = "bar2"
console.log(c) 
// { field: "bar" }

### What is the expected behavior?
Ideal behaviour is that readonly-mode would be configurable so that we can intentionally make changes and protect it at other times.

config.get() making it readonly seems like an unwanted side-effect.

In my case, I have made a wrapper module that updates the config based on environment variables matching <prefix>(<field><delim>)+ = "value"

This works fine unless someone calls config.get() before my module executes.

//works
let config = require("config");
process.env.MYAPP_field = "bar"
require(env2object).env2job(config, { prefix: "MYAPP_" } );
// { field: "bar" } overridden

//fails
let config = require("config");
process.env.MYAPP_field = "bar"
config.get("field");
require(env2object).env2job(config, { prefix: "MYAPP_" } );
// { field: "foo" } no override

### Please tell us about your environment:

 -  node-config version: 1.28.1
 -  node-version: v8.9.2

**Comment by markstos** [comment]
This behavior is an intentional design design to provide the safety guarantees of immutability once you start using the module by calling `.get()`, but still allows a window to make changes before immutably is enabled-- useful for testing different configurations. 

There are multiple solutions that allow you to reload node-config if you need to start over with new values. 

If you search the project for [immutable], you'll find over two dozen issues referencing the topic and 6 mentions on the wiki. 

https://github.com/lorenwest/node-config/search?q=immutable&type=Issues&utf8=%E2%9C%93

In your case, perhaps you want to use one of the config-reloading solutions. This is similar to the immutable design pattern where you make a new copy of an immutable data structure rather than modify it. 

Some modules that help reload cached modules include https://www.npmjs.com/package/require-reload and https://www.npmjs.com/package/module-invalidate

**Comment by tombburnell** [comment]
Hi Mark - Thanks for clarifying how and why it is the way it is. Could you elaborate one how one of the config-reloading options you mentioned would help? I'm not quite following.

Essentially, I am trying to provide a mechanism for setting deep values via environment variables using environment variables without requiring to configure each one specifically in the repo and on a one environment variable->one field basis (rather than NODE_CONF which does many at a time)

Thanks, Tom

**Comment by markstos** [comment]
Tom,

It sounds like we already support the feature you are looking for. Have you
found the docs about `custom-environment-variables.json` on our Environment
Variables wiki page?

https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables

    Mark
