### ISSUE TITLE
Here wrongly use global config as target

### ISSUE THREAD

**Issue by zyf0330** [lorenwest/node-config#476]
https://github.com/lorenwest/node-config/blob/955db09ca5cb5be81406d2ef1709648e2b6b9dce/lib/config.js#L193

It should be `util.makeImmutable(this);`

**Comment by markstos** [comment]
I believe the current code is correct. Many sub-objects will have a `get()` method, but we want the entire config to be immutable at this point, not just a sub-object, which is why `config` is used here and not `this`. 

If you feel certain there's a bug, please a pull request with a test case that fails.

**Comment by zyf0330** [comment]
I use attachProto and extendDeep of utils to create my config obj, but this kind of get property whose value is rawConfig fails.
Why just makeImmutate once and set a boolean mark? I don't want to judge this design. 
So it is better for me to keep old node-config version.

**Comment by markstos** [comment]
@patrickpilch See feedback here about `raw` and immutability.
