### ISSUE TITLE
Let me get the whole config object by calling get()

### ISSUE THREAD

**Issue by light24bulbs** [lorenwest/node-config#489]
Just let me call config.get() to get the whole object.    That would be a very intuitive behavior.

**Comment by lorenwest** [comment]
**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

Before submitting a bug report, please search the issue tracker the wiki first. Many issues have already been discussed.

The wiki is located at: https://github.com/lorenwest/node-config/wiki

### I'm submitting a ... 
  - [  ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
*If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

### What is the expected behavior?

### Please tell us about your environment:

 -  node-config version: x.x.x
 -  node-version: x.x.x
 
### Other information

(e.g. are you using an environment besides Node.js?)
