### ISSUE TITLE
Error: Config file /config/custom-environment-variables.js cannot be read

### ISSUE THREAD

**Issue by agroves333** [lorenwest/node-config#573]
### I'm submitting a ... 
  - [X] bug report
  - [  ] feature request
  - [  ] support request or question 

### What is the current behavior?
When using config/default.json and config/development.json and running `NODE_ENV=development node start.js`, I'm getting the following error:
`Error: Config file /config/custom-environment-variables.js cannot be read
`

The error is due to invalid file parsing [here](https://github.com/lorenwest/node-config/blob/master/lib/config.js#L1072) which states "Map environment variables into the configuration if a mapping file,`custom-environment-variables.EXT` exists."

Also, [https://github.com/lorenwest/node-config/blob/master/lib/config.js#L771](parseFile()) should return null if the file is not found instead of throwing error.

### What is the expected behavior?
If custom-environment-variable.js isn't present, then it should be ignored.

### Please tell us about your environment:

 -  node-config version: 3.2.2
 -  node-version: 12.4.0
 
### Other information

config/default.json
```
{
	"GraphQL": {
		"uri": "https://api.popodds.com"
	}
}
```

config/development.json
```
{
	"GraphQL": {
		"uri": "http://localhost:8080"
	}
}
```

Usage:
```
import config from 'config';
const uri = config.get('GraphQL.uri');
```

**Comment by markstos** [comment]
@agroves333 In case someone else runs into the same issue, please leave a comment explaining what the root cause was (since this appears not be a bug)

**Comment by zypA13510** [comment]
I'm running into this too. It was fine when I run node from command-line directly, but throwing this error when I run it in docker. Will try to investigate.

**Comment by zypA13510** [comment]
After some testing, I can confirm that #561 introduced this bug. Downgrading to 3.1.0 works for the moment.

**Comment by lorenwest** [comment]
Bump @iMoses - any insight into this issue?

**Comment by markstos** [comment]
@agroves333 or @zypA13510 Could you contribute a failing test which shows the bug in action. I agree it sounds like a regression we'd like to fix.

**Comment by markstos** [comment]
I looked into this. What I found is that although we don't have direct tests for `getCustomEnvVars()`, we have indirect coverage for both the cases where the custom env file is present and when it is not present.

We currently currently return `null` for ENOENT-- when the file is missing. We only throw if there's another problem, like a file that can't be parsed.

I think the improvement we can make here it to improve our error message to include the error code. That will help users and US track down the alternate error condition that's involved here.  I'll make that commit now.

**Comment by markstos** [comment]
@lorenwest I've now pushed 8a9b5719f0f51286a66f8e5c6ff96bde62d0caa7 for improve diagnostics. 

It turns out that while we have coverage for the custom Env file being present or absent, we don't have coverage for *this* case, which is an error due to a reason other then the file being absent or unparseable. The improved diagnostic I just pushed will surface exactly what error people are running into. 

I'm leaving this open until there's a release which includes this update.

**Comment by markstos** [comment]
Wrong SHA. Let's try  e334cfaa06b2347f0f8ae0c2f0b65451f4b351c5

**Comment by lorenwest** [comment]
Looks good - I'll push a point release.

**Comment by lorenwest** [comment]
Published today in @3.2.3

**Comment by zypA13510** [comment]
Just tried the new release, now I can see why it failed, and it looks like the problem was elsewhere indeed. Thank you @markstos.

**Comment by brakop** [comment]
Apologies for the newb query, but can someone clarify what the workaround here is? I had my a vue app running and compiling with no issues on 3.11.0, upgraded to 4.0.4, got this exact error message, then removed @vue/cli and re-installed 3.11.0 and still get this error. I'm presuming that's because some dependency has been uplifted at the same time? Also, can I just create an empty custom-environment-variables.js somewhere and bypass this? (Tried to do this in a \src\config\ directory to no avail.) Appreciate any suggestions, kind of left with deinstalling NPM and vue cli and maybe starting over?

**Comment by markstos** [comment]
@zypA13510 Had a problem elsewhere in his app but didn't share what it was.  In `node-config` 3.2.3 there is error log that explains why the file can't be read if it's something unexpected. We are only aware of this being triggered by a problem in your app. Your error logs will you if there's an unexpected error.
