### ISSUE TITLE
Unexpected loading order for files with different .EXT with two paths injection

### ISSUE THREAD

**Issue by jguillod** [lorenwest/node-config#609]
### I'm submitting a ... 
  - [X] bug report

### What is the current behavior?

Load two sources config directories:

```js
process.env["NODE_CONFIG_DIR"] = `/path/to/configs/common.config/` + require('path').delimiter + `/path/to/configs/${SERVICE}.config`;
const conf = require("config");
```

- with all `.js` config files `conf.getConfigSources()` gives the expected loading order:

```js
[
  '/path/to/configs/common.config/default.js',
  '/path/to/configs/client-gateway.config/default.js',
  '/path/to/configs/common.config/development.js',
  '/path/to/configs/client-gateway.config/development.js'
]
```
- with a mixed of `.js` and `.json` files `conf.getConfigSources()` gives an unexpected loading order:

```js
[
  '/path/to/configs/common.config/default.js',
  '/path/to/configs/client-gateway.config/default.json',
  '/path/to/configs/client-gateway.config/development.js',
  '/path/to/configs/common.config/development.json'
]
```

### What is the expected behavior?
Expected order is `default` for 1st path, then `default` for 2nd path, then `development` for 1st path, then `development` for 2nd path, whatever the file extensions are:

```js
[
  '/path/to/configs/common.config/default.js',
  '/path/to/configs/client-gateway.config/default.json',
  '/path/to/configs/common.config/development.json',
  '/path/to/configs/client-gateway.config/development.js'
]
```

It appears that at each step (`default.EXT`, then `development.EXT`) files are taken by basename sort order (i.e. EXT: js, then json) and not by source directory order. This appears a confusing bug since when a developer changes a file EXT the loading order will also change.

### Please tell us about your environment:

 -  node-config version: 3.3.1
 -  node-version: v14.2.0
 
### Other information

Thanks !

**Comment by markstos** [comment]
I've reviewed our documentation about file load order, which is here:

https://github.com/lorenwest/node-config/wiki/Configuration-Files

We do promise to load files in a particular order, but we don't promise to merge multiple directories in a particular way. While we do have a stable order that we load extensions in, that is not documented. 

What you are doing here is overriding the default configuration file with customer-specific values.

I recommend using the the custom `deployment` and `instance` values we already provide for that, which can be controlled with `NODE_ENV` and `NODE_APP_INSTANCE`. Then rather than having files which have the same name except for their extension, you can have:

    default.js
    default-customer.json
    development.json
    development-customer.js

You can still spread them across two directories if you like.

I'm concerned what would be a "fix" for your expectations would break someone else's expectations where they depend on the load order as it currently is, which prioritizes the file extension as a sort method.

Actually, this situation somewhat makes me regret starting to support multiple directories. The file load order was already complex enough before.
