### ISSUE TITLE
Configurable NODE_CONFIG_DIR not working

### ISSUE THREAD

**Issue by Jacob-Mahoney** [lorenwest/node-config#633]
### I'm submitting a ... 
  - [ x ] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
Changing the NODE_CONFIG_DIR doesn't seem to be working.

### What is the expected behavior?
To have the package pick up my configuration settings, no matter where they are at.

### Please tell us about your environment:

 -  node-config version: 3.3.3
 -  node-version: 14.4.0
 
### Other information
```
process.env["NODE_CONFIG_DIR"] = "./testing";
import config from "config";
console.log(config.get("database.host"));
```

This ^ does not work. Whenever I create a new directory in my project directory named `testing` and create a file named `default.json` within it, then run this and try to get a configuration setting, I get an error saying `Error: Configuration property "database.host" is not defined`.

**Comment by gianpesto** [comment]
i had the same problem using es6 modules instead of commonJS. The problem here is that the imports get hoisted and the ENV var that you have set, is being set after config has been imported.

see: https://stackoverflow.com/questions/51729775/node-programmatically-set-process-environment-variables-not-available-to-importe
