### ISSUE TITLE
Include js-yaml as dependencies or peerDependencies

### ISSUE THREAD

**Issue by AbrahamTewa** [lorenwest/node-config#647]
### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
I'm on a project using NextJS (probably not relevant here).

1. Install on production mode

```
npm ci --prod
```

2. Start the project:

```
npm start
```

The following message is displayed:
```
No YAML parser loaded.  Suggest adding js-yaml dependency to your package.json file.
```

And the configuration is not loaded : 
* It doesn't appear when displaying the `config.util.getConfigSources()`
* The SUPPRESS_NO_CONFIG_WARNING message is displayed

The problem disapper if reproduce the same steps after added `js-yaml` package in my dependencies.

### What is the expected behavior?
No message.

### Please tell us about your environment:

 -  node-config version: 3.3.3
 -  node-version: 14.15.5

**Comment by lorenwest** [comment]
This is the expected behavior.  The `config` project runs natively with .json files, and can support many different flavors of configuration, including YAML.

The problem is, projects generally only use one file format type (their preferred type), and they don't want to be burdened by downloading every library for every possible configuration type.  

Accordingly, per the [File Formats](https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-formats) documentation, it specifies if you choose to use any of these file types that require a library, it is your responsibility to add a dependency to that library in your package.json.

**Comment by markstos** [comment]
The workaround is specify this other library in the project that uses `node-config` as a dependency.
