### ISSUE TITLE
Dependencies also using node-config can unexpected "override" config values.

### ISSUE THREAD

**Issue by andrewkolos** [lorenwest/node-config#652]
### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?

[Demo repo](https://github.com/andrewkolos/node-config-demo).

Lets suppose we have our `config/default.json` file set up as follows:

```json
{
  "MyParam": "DemoValue1"
}
```

And we have our main `index.js` file, which just retrieves and prints the value of `MyParam`:

```js
const config = require('config')
const fakeDependency = require('fake_dependency')

console.log(`The value of MyParam is ${config.get('MyParam')}`)
```

Notice `fake_dependency`. This is a fictitious npm module who's main file starts as follows:

```js
const config = require('config')
```

So, `fake_dependency` also uses `config`. Examining it's only config file, `config/default.json`, we find:

```json
{
  "MyParam": "FakeDependencyValue"
}
```
Unexpectedly, `fake_depedency` will see the value of `MyParam` as `DemoValue1` instead of `FakeDepdencyValue`

### What is the expected behavior?

Calling `config.get('MyParam')` from within the `fake_dependency` should yield `FakeDependencyValue`, not `DemoValue`. Is this intended?

### Please tell us about your environment:

 -  node-config version: 3.3.6
 -  node-version: v14.15.1

**Comment by lorenwest** [comment]
This is the expected behavior.  By default (and by design) there is a single config directory containing all configurations.  If a submodule uses config, it must inform the containing module of the variables it uses so the containing module can supply values for those configurations.

This default behavior can be overridden by specifying a path for the configuration directory. See `NODE_CONFIG_DIR` in the `Configuration Files` section of the [wiki](https://github.com/lorenwest/node-config/wiki).

**Comment by lorenwest** [comment]
You may also be interested in the [Sub Module Configuration](https://github.com/lorenwest/node-config/wiki/Sub-Module-Configuration) section of the wiki.
